title: Virtual Science Week 2020
description: ""

# url: http://brianmaierjr.github.com/long-haul
baseurl: "/VSW2020"
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Gallery
    url: /gallery

# social:
#   github: brianmaierjr
#   twitter: brianmaierjr
#   facebook: brianmaierjr
#   email: brimaidesigns@gmail.com
#   linkedin: brianmaierjr

# google_analytics: "UA-58263416-1"

disqus:
    shortname: chevs
